language: node_js
node_js:
  - '6'
before_script:
  - echo 'Canada/Pacific' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
branches:
  except:
    - /^greenkeeper-.*$/
notifications:
  slack:
    on_pull_requests: false
    on_success: change
    on_failure: always
    rooms:
      secure: A2INWkigK/OQgOjKugaHGBDsGcjcYeiK9haNG6nvmeqsfBpNQg0c7nrLABqsDW1Mg0VbDMWPzx31/DdF3vKo/bCkSKH4/v3ky7zBgGXUPyh2ZArT/CYd7kK/R6Z8o6hHhGI+sdFuxa5CwIDVNKZqEbwy9dxlBpjeksxHBpwU9Ik2zxPVaB3scHSLbxf4RR73ltVvhn+WGXkr1BvI9t4yxynbKHQfZPCZUA3RRbd873LEE70/tXsa/J8hndNJYWrCUmRsIfaOG9g1QebCxcuVyPcpD/fj6buudctrI7G9tb2nuNSfaxgKKtgc6Ctr0+r6FAq8nUPqbvESAUyq5BBcHcpPFX9SBui9r9YyIdWZWvB0fwL3pNuipWUq191M8ilUna4n3ZpPe7TfTDof5ry6WmltXR0rAwBmdcwZeH3HjNacdLqtzLceHgYvbkQSeHyStdoL5zKdgRh8fV+x09GWo3J63dkHCWNEmxc567UCWayBQ724OlzEkDHNaP8b0ECJOCdjwsStnza54LEUmxkpa/oXILkO0oIFvzqzSvEg7dJZWTo8hLwXChkBvm03AYcUYzXFI3IhKKlkEi/gnGf8bG8hpzO6pKZFrjkV6884rLYAopgHP7yOvBk0bM0VI0HdeTI9odKgoVzKNCk5fHip2tMK2BlKEoMBdQ8xIEyFxLg=
